# -*- coding: utf-8 -*-
"""
Style template generated by sqsl-style-cloner.
Compatible with sqsl-article-to-wechat/scripts/render_wechat_html.py.
"""

import re
import html

# 风格元信息
STYLE_NAME = "cloned_3e3e3e"
STYLE_DISPLAY_NAME = "复刻风格_重访阿芋：是制帽"
PRIMARY_COLOR = "#3E3E3E"
ACCENT_COLOR = "#A7A56D"
TEXT_COLOR = "#3E3E3E"
BG_COLOR = "#FFFFFF"
CALLOUT_BG = "#F4F7FA"
CALLOUT_BORDER = "#3E3E3E"

class ClonedStyle_Cloned_3e3e3e:
    name = "cloned_3e3e3e"
    display_name = "复刻风格_重访阿芋：是制帽"
    
    def render_doc_start(self):
        return f"""<section style="max-width:677px;margin:0 auto;background:{BG_COLOR};font-family:PingFangSC-light,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:{TEXT_COLOR};line-height:1.75;letter-spacing:0.3px;box-sizing:border-box;">"""

    def render_h1(self, title, tag=""):
        tag_html = f'<p style="font-size:11px;font-weight:700;color:{ACCENT_COLOR};letter-spacing:2.5px;margin:0 0 10px;text-transform:uppercase;"><span leaf="">{tag}</span></p>' if tag else ""
        return f"""
  <!-- 主标题 -->
  <section style="padding:28px 22px 14px;text-align:center;box-sizing:border-box;">
    {tag_html}
    <p style="font-size:24px;font-weight:700;line-height:1.35;color:{PRIMARY_COLOR};margin:0 0 12px;letter-spacing:1px;"><span leaf="">{title}</span></p>
  </section>
  <section style="text-align:center;margin:6px 0 24px;line-height:0;box-sizing:border-box;">
    <section style="display:inline-block;width:36px;height:2px;background:{PRIMARY_COLOR};"><span leaf=""><br/></span></section>
  </section>"""

    def render_h2(self, idx, text):
        num_str = f"{idx:02d}"
        return f"""
  <!-- H2 章节标题 -->
  <section style="margin:28px 22px 14px;box-sizing:border-box;">
    <p style="font-size:18px;font-weight:700;color:{PRIMARY_COLOR};margin:0;padding-left:10px;border-left:4px solid {PRIMARY_COLOR};line-height:1.4;">
      <span style="color:{ACCENT_COLOR};margin-right:6px;font-family:ui-monospace,Menlo,monospace;">{num_str}</span><span leaf="">{text}</span>
    </p>
  </section>"""

    def render_h3(self, text, is_highlight=False):
        badge = f'<span style="background:#FFF0E6;color:{ACCENT_COLOR};padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;margin-left:8px;vertical-align:middle;display:inline-block;"><span leaf="">重点</span></span>' if is_highlight else ''
        return f"""
  <!-- H3 小标题 -->
  <section style="padding:14px 22px 6px;box-sizing:border-box;">
    <p style="font-size:16px;font-weight:700;line-height:1.4;color:{PRIMARY_COLOR};margin:0;letter-spacing:0.5px;">
      <span leaf="">{text}</span>{badge}
    </p>
  </section>"""

    def render_callout(self, content):
        return f"""
  <!-- 引用/重点卡片 -->
  <section style="background:{CALLOUT_BG};border-left:3px solid {CALLOUT_BORDER};padding:14px 18px;margin:18px 22px;border-radius:0 4px 4px 0;box-sizing:border-box;">
    <p style="margin:0;font-size:13.5px;color:{PRIMARY_COLOR};line-height:1.65;text-align:justify;"><span leaf="">{content}</span></p>
  </section>"""

    def render_paragraph(self, content):
        return f"""
  <!-- 段落正文 -->
  <section style="font-size:14px;font-family:PingFangSC-light;padding:0px 22px;line-height:1.75;box-sizing:border-box;margin:12px 0;">
    <p style="white-space:normal;margin:0px;padding:0px;box-sizing:border-box;text-align:justify;"><span leaf="">{content}</span></p>
  </section>"""

    def render_list_item(self, content, is_ordered=False, num=1):
        bullet = f"{num}." if is_ordered else "•"
        return f"""
  <!-- 列表项 -->
  <section style="font-size:14px;font-family:PingFangSC-light;padding:3px 22px 3px 36px;line-height:1.75;box-sizing:border-box;position:relative;">
    <p style="white-space:normal;margin:0px;padding:0px;box-sizing:border-box;text-align:justify;">
      <span style="position:absolute;left:22px;color:{PRIMARY_COLOR};font-weight:bold;">{bullet}</span><span leaf="">{content}</span>
    </p>
  </section>"""

    def render_image(self, b64_or_src, caption=""):
        caption_html = f"""
  <section style="text-align:center;margin:0 0 20px;line-height:1.5;box-sizing:border-box;padding:0 22px;">
    <p style="margin:4px 0 0;font-size:12px;color:#888888;font-family:PingFangSC-light;"><span leaf="">{caption}</span></p>
  </section>""" if caption else '<section style="margin-bottom:14px;"></section>'
        
        return f"""
  <!-- 插图卡片 -->
  <section style="text-align:center;margin:18px 0 8px;line-height:0;width:100%;box-sizing:border-box;">
    <section style="max-width:100%;vertical-align:middle;display:inline-block;width:90%;height:auto;box-sizing:border-box;">
      <img src="{b64_or_src}" style="vertical-align:middle;max-width:100%;width:100%;box-sizing:border-box;display:block;border-radius:4px;box-shadow:0 2px 10px rgba(0,0,0,0.05);" alt="{caption}"/>
    </section>
  </section>{caption_html}"""

    def render_code_block(self, code_text, lang=""):
        escaped_code = html.escape(code_text)
        return f"""
  <!-- 代码块 -->
  <section style="margin:16px 22px;border-radius:6px;background:#1E293B;padding:14px 16px;box-sizing:border-box;overflow-x:auto;">
    <p style="margin:0 0 6px;font-size:11px;color:#94A3B8;font-family:ui-monospace,Menlo,monospace;text-transform:uppercase;">{lang or 'CODE'}</p>
    <pre style="margin:0;font-family:ui-monospace,Menlo,Monaco,Consolas,monospace;font-size:12.5px;color:#F8FAFC;line-height:1.55;white-space:pre-wrap;word-break:break-all;"><code>{escaped_code}</code></pre>
  </section>"""

    def render_table(self, headers, rows):
        th_cells = "".join([f'<th style="border:1px solid #E2E8F0;background:#F8FAFC;color:{PRIMARY_COLOR};font-size:13px;font-weight:600;padding:8px 12px;text-align:left;">{h}</th>' for h in headers])
        tr_rows = []
        for r in rows:
            td_cells = "".join([f'<td style="border:1px solid #E2E8F0;font-size:12.5px;color:#334155;padding:8px 12px;">{cell}</td>' for cell in r])
            tr_rows.append(f'<tr>{td_cells}</tr>')
        tbody_html = "".join(tr_rows)
        return f"""
  <!-- 表格 -->
  <section style="margin:16px 22px;overflow-x:auto;box-sizing:border-box;">
    <table style="width:100%;border-collapse:collapse;border:1px solid #E2E8F0;text-align:left;">
      <thead><tr>{th_cells}</tr></thead>
      <tbody>{tbody_html}</tbody>
    </table>
  </section>"""

    def render_hr(self):
        return f"""
  <section style="text-align:center;margin:28px 22px;line-height:0;box-sizing:border-box;">
    <section style="display:inline-block;width:30px;height:1px;background:#E2E8F0;"><span leaf=""><br/></span></section>
  </section>"""

    def render_footer(self, author="AI 工作台", note=""):
        return f"""
  <section style="text-align:center;margin:32px 22px 18px;line-height:0;box-sizing:border-box;">
    <section style="display:inline-block;width:30px;height:1px;background:#CBD5E1;"><span leaf=""><br/></span></section>
  </section>
  <section style="text-align:center;color:{TEXT_COLOR};font-size:12px;font-family:PingFangSC-light;padding:0px 22px;line-height:1.75;margin:16px 0px 24px;box-sizing:border-box;">
    <p style="margin:0px;padding:0px;font-weight:500;color:{PRIMARY_COLOR};box-sizing:border-box;"><span leaf="">排版：{STYLE_DISPLAY_NAME}</span></p>
  </section>"""

STYLE_INSTANCE = ClonedStyle_Cloned_3e3e3e()
